// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Yj9ZeV5tUF8e_K05vxHbYrVJ7nQvW84',
    appId: '1:1018586798653:android:904da780b6004266cae854',
    messagingSenderId: '1018586798653',
    projectId: 'houseproject-18f44',
    storageBucket: 'houseproject-18f44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Yj9ZeV5tUF8e_K05vxHbYrVJ7nQvW84',
    appId: '1:1018586798653:ios:904da780b6004266cae854',
    messagingSenderId: '1018586798653',
    projectId: 'houseproject-18f44',
    storageBucket: 'houseproject-18f44.appspot.com',
    iosBundleId: 'com.example.property',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5Yj9ZeV5tUF8e_K05vxHbYrVJ7nQvW84',
    appId: '1:1018586798653:macos:904da780b6004266cae854',
    messagingSenderId: '1018586798653',
    projectId: 'houseproject-18f44',
    storageBucket: 'houseproject-18f44.appspot.com',
    iosBundleId: 'com.example.property',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Yj9ZeV5tUF8e_K05vxHbYrVJ7nQvW84',
    appId: '1:1018586798653:web:904da780b6004266cae854',
    messagingSenderId: '1018586798653',
    projectId: 'houseproject-18f44',
    authDomain: 'houseproject-18f44.firebaseapp.com',
    storageBucket: 'houseproject-18f44.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5Yj9ZeV5tUF8e_K05vxHbYrVJ7nQvW84',
    appId: '1:1018586798653:windows:904da780b6004266cae854',
    messagingSenderId: '1018586798653',
    projectId: 'houseproject-18f44',
    storageBucket: 'houseproject-18f44.appspot.com',
  );
} 