name: Deploy Flutter Web to gh-pages branch

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Enable web
        run: flutter config --enable-web

      - name: Build web (base-href = /TESTHOME/)
        run: |
          set -euxo pipefail
          flutter build web --release --base-href /TESTHOME/
          cp build/web/index.html build/web/404.html
          test -f build/web/index.html
          head -n 15 build/web/index.html || true

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
          enable_jekyll: false
          force_orphan: true


